### ISSUE TITLE
App still maintained?

### ISSUE THREAD

**Issue by IzzySoft** [KarimElghamry/cryptoholic#10]
Hi @KarimElghamry, I just wonder if the app is still maintained. The only update after ~4 years was an adjustment to the Readme, but as far as I can see no code updates since 7/2019. Are you still planning to work on it?

**Comment by KarimElghamry** [comment]
Hello @IzzySoft, Thanks for checking out the app. Currently, I'm not actively working on the app since it was a side project of mine. I haven't had the time to progressively develop this app further. I might have to revisit the app sometime in the future to continue it's development, but I doubt it'll be anytime soon.

**Comment by IzzySoft** [comment]
Mind me [marking it](https://apt.izzysoft.de/packages/com.example.cryptoholic/) as "currently unmaintained" then, disable update checks – and just leaving this issue open so you remember giving me a ping should you pick up again?

**Comment by KarimElghamry** [comment]
@IzzySoft feel free to to go ahead and do so. I'll close the issue in the meantime and reopen it once I get back onto the app development. Thanks.

**Comment by IzzySoft** [comment]
OK, done. Please give me a ping from there then should the day come. All the best for you!

**Comment by IzzySoft** [comment]
Oof, one more thing @KarimElghamry – a scan just brought up an issue with the APK, it's signed with an expired debug key ([see here](https://gitlab.com/IzzyOnDroid/repo/-/issues/477) for some background and details). Any chance you could provide a properly signed APK? If not, maybe I need to go beyond just marking it "currently unmaintained" and (temporarily) remove it. Can of course then be added back once you pick up again and provide a properly signed APK.

**Comment by IzzySoft** [comment]
Looks like "real life" gets you occupied too much currently to fix the signing. I'll remove the app from my repo now (as suggested) – and please feel welcome to reopen this issue and reach out to me once you have a new release ready.

Thanks, and all the best meanwhile!
