### ISSUE TITLE
switch bottom tab ,text in searchbar in first page lost

### ISSUE THREAD

**Issue by ashamp** [KarimElghamry/cryptoholic#5]
![121212111](https://user-images.githubusercontent.com/6055170/64063186-762b9480-cc23-11e9-9c9e-5ea4f2204a63.gif)

**Comment by ashamp** [comment]
How can i keep "Market" screen not rebuild?

**Comment by KarimElghamry** [comment]
It's because the bloc gets disposed, I will fix that right now and push to to the branch develop. I will tell you as soon as I fix that.

**Comment by KarimElghamry** [comment]
it is working now. The changes have been pushed to `develop` branch.

![sample](https://user-images.githubusercontent.com/46113985/64067520-fa811600-cc29-11e9-9053-77133e54cf62.gif)

**Comment by ashamp** [comment]
thank you very much,I will learning it 😀
