### ISSUE TITLE
The method 'CachedNetworkImageProvider.load' has fewer positional arguments than those of overridden method 'ImageProvider.load'.

### ISSUE THREAD

**Issue by ChanchleshSuryawanshi** [KarimElghamry/cryptoholic#9]
Is the source code obsolete?

> Compiler message:
../../Documents/Workspace/flutter/.pub-cache/hosted/pub.dartlang.org/cached_netw
ork_image-1.1.0/lib/src/cached_network_image_provider.dart:42:24: Error: The
method 'CachedNetworkImageProvider.load' has fewer positional arguments than
those of overridden method 'ImageProvider.load'.
  ImageStreamCompleter load(CachedNetworkImageProvider key) {
                       ^
../../Documents/Workspace/flutter/packages/flutter/lib/src/painting/image_provid
er.dart:403:24: Context: This is the overridden method ('load').
  ImageStreamCompleter load(T key, DecoderCallback decode);

Error: The method 'CachedNetworkImageProvider.load' has fewer positional arguments than
those of overridden method 'ImageProvider.load'.

**Comment by anujrathore131** [comment]
Yup, same issue if you solved it please guide me..
